-- ============================================================================
-- Migration 002: Autonomous Execution System Tables
-- ============================================================================
-- Creates the tables, indexes, RLS policies, and schema additions needed
-- by the autonomous executor to queue approvals, send notifications, and
-- track batch execution context.
-- ============================================================================


-- ============================================================================
-- 1. pending_approvals — Items queued for human review
-- ============================================================================
-- The autonomous executor queues actions here when confidence is below the
-- auto-execute threshold or when the change exceeds guardrail limits.
-- A human reviewer can then approve, reject, or let the item expire.

CREATE TABLE IF NOT EXISTS pending_approvals (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    campaign_id     UUID REFERENCES campaigns(id) ON DELETE CASCADE,
    keyword_id      UUID REFERENCES keywords(id) ON DELETE SET NULL,
    action_type     TEXT NOT NULL CHECK (action_type IN (
                        'bid_change', 'negative_keyword', 'budget_change', 'strategy_change'
                    )),
    current_value   NUMERIC DEFAULT 0,
    recommended_value NUMERIC DEFAULT 0,
    confidence      NUMERIC DEFAULT NULL,
    change_pct      NUMERIC DEFAULT NULL,
    reasons         JSONB DEFAULT '[]'::jsonb,
    metadata        JSONB DEFAULT '{}'::jsonb,
    status          TEXT NOT NULL DEFAULT 'pending' CHECK (status IN (
                        'pending', 'approved', 'rejected', 'expired'
                    )),
    resolved_by     UUID DEFAULT NULL,
    resolved_at     TIMESTAMPTZ DEFAULT NULL,
    created_at      TIMESTAMPTZ DEFAULT now()
);

COMMENT ON TABLE pending_approvals IS
    'Items queued for human review by the autonomous executor. '
    'Actions that fall below confidence thresholds or exceed guardrails land here '
    'instead of being auto-applied.';


-- ============================================================================
-- 2. notifications — In-app notifications from the autonomous system
-- ============================================================================
-- The autonomous executor, alerting system, and experiment engine all write
-- notifications here. The client polls for unread counts and displays them
-- in a notification center.

CREATE TABLE IF NOT EXISTS notifications (
    id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    seller_id   UUID DEFAULT NULL,
    title       TEXT NOT NULL,
    message     TEXT NOT NULL,
    severity    TEXT NOT NULL DEFAULT 'info' CHECK (severity IN (
                    'info', 'warning', 'critical'
                )),
    category    TEXT NOT NULL DEFAULT 'autonomous' CHECK (category IN (
                    'autonomous', 'alert', 'experiment', 'system'
                )),
    metadata    JSONB DEFAULT '{}'::jsonb,
    is_read     BOOLEAN DEFAULT FALSE,
    created_at  TIMESTAMPTZ DEFAULT now()
);

COMMENT ON TABLE notifications IS
    'In-app notifications generated by the autonomous executor, alerting pipeline, '
    'experiment system, and other background processes. Each notification belongs to '
    'a seller and carries severity and category for filtering.';


-- ============================================================================
-- 3. Add columns to autonomous_logs (idempotent)
-- ============================================================================
-- approval_tier tracks which tier (auto / review / manual) an action fell into.
-- batch_id groups actions that were executed together in a single autonomous run.

ALTER TABLE autonomous_logs
    ADD COLUMN IF NOT EXISTS approval_tier TEXT DEFAULT NULL;

ALTER TABLE autonomous_logs
    ADD COLUMN IF NOT EXISTS batch_id TEXT DEFAULT NULL;

COMMENT ON COLUMN autonomous_logs.approval_tier IS
    'Which approval tier the action fell into: auto, review, or manual.';

COMMENT ON COLUMN autonomous_logs.batch_id IS
    'Groups actions executed together in a single autonomous executor run.';


-- ============================================================================
-- 4. Performance indexes
-- ============================================================================

-- Approval queue — filter by status for the review UI
CREATE INDEX IF NOT EXISTS idx_pending_approvals_status
    ON pending_approvals(status);

-- Approval queue — filter by campaign for campaign-level views
CREATE INDEX IF NOT EXISTS idx_pending_approvals_campaign_id
    ON pending_approvals(campaign_id);

-- Notifications — fast unread-count query per seller
CREATE INDEX IF NOT EXISTS idx_notifications_seller_unread
    ON notifications(seller_id, is_read);

-- Autonomous logs — look up all actions in a given batch
CREATE INDEX IF NOT EXISTS idx_autonomous_logs_batch_id
    ON autonomous_logs(batch_id);


-- ============================================================================
-- 5. Row-Level Security
-- ============================================================================

-- ---------- pending_approvals ----------
ALTER TABLE pending_approvals ENABLE ROW LEVEL SECURITY;

-- Authenticated users can read all pending approvals
-- (the UI filters by seller on the client side; all sellers in an org
--  may need visibility into the approval queue).
DO $$ BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_policies
        WHERE tablename = 'pending_approvals' AND policyname = 'pending_approvals_select_authenticated'
    ) THEN
        CREATE POLICY pending_approvals_select_authenticated
            ON pending_approvals
            FOR SELECT
            TO authenticated
            USING (true);
    END IF;
END $$;

-- Authenticated users can update (approve/reject) approvals that belong to
-- campaigns they own (seller_id match through campaigns table).
DO $$ BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_policies
        WHERE tablename = 'pending_approvals' AND policyname = 'pending_approvals_update_own'
    ) THEN
        CREATE POLICY pending_approvals_update_own
            ON pending_approvals
            FOR UPDATE
            TO authenticated
            USING (
                EXISTS (
                    SELECT 1 FROM campaigns c
                    WHERE c.id = pending_approvals.campaign_id
                      AND c.seller_id = auth.uid()
                )
            )
            WITH CHECK (
                EXISTS (
                    SELECT 1 FROM campaigns c
                    WHERE c.id = pending_approvals.campaign_id
                      AND c.seller_id = auth.uid()
                )
            );
    END IF;
END $$;

-- ---------- notifications ----------
ALTER TABLE notifications ENABLE ROW LEVEL SECURITY;

-- Users can read their own notifications
DO $$ BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_policies
        WHERE tablename = 'notifications' AND policyname = 'notifications_select_own'
    ) THEN
        CREATE POLICY notifications_select_own
            ON notifications
            FOR SELECT
            TO authenticated
            USING (seller_id = auth.uid());
    END IF;
END $$;

-- Users can update (mark as read) their own notifications
DO $$ BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_policies
        WHERE tablename = 'notifications' AND policyname = 'notifications_update_own'
    ) THEN
        CREATE POLICY notifications_update_own
            ON notifications
            FOR UPDATE
            TO authenticated
            USING (seller_id = auth.uid())
            WITH CHECK (seller_id = auth.uid());
    END IF;
END $$;


-- ============================================================================
-- Done.
-- ============================================================================
